services:
  qr-generator:
    container_name: qr-generator-server
    image: ghcr.io/rheinmir/qr-generator:latest
    build: .
    restart: unless-stopped
    ports:
      - "5175:3000"
    environment:
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
